### ISSUE TITLE
关于与作者私下交流的请求

### ISSUE THREAD

**Issue by free001a** [Chupeng24/git-demo#1]
您好，冒昧打扰，此举可能违反了社区礼仪，但是我别无他法，请海涵。我对Learning to Dispatch for Job Shop Scheduling via Deep Reinforcement Learning这篇论文和代码很感兴趣，但是有一些问题无人可询问讨论，并且苦思不得其解，非常希望获得别人的指点。我注意到您曾与作者交流过，请问我可以和您交换一下联系方式吗，我可以有偿付费咨询，因为我真的很需要帮助，我的微信是FLYFREE001a。

或者您认为此举侵犯了您的隐私，我在该论文作者的该项目最新的issue中写明了我的困惑，希望可以得到指点。

感激不尽！

**Comment by Chupeng24** [comment]
你可以问我，那个程序我看了几遍了

**Comment by Chupeng24** [comment]
联系方式/微信号：15914467363
